language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
sudo: false
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: q2LZrsGha9EEWzHYLhDVq2Q711WjlWOxOcLNFBIIIDSYYsAJB/aYunCD6akL6JZ01XYKBYackS1BOuXDuCFMI2z0k2tk4oCODbEMreB24wQmpnLd3/vZMjK3tRRFvj3KExYrt2eZfJjxpFsuj2Tl+Jj7p58qgA6mnW+ArW273SM=
  file:
    - 'parse-link.js'
    - 'parse-link.min.js'
  on:
    tags: true
